"""added sku column to product model

Revision ID: 1601b5c01655
Revises: 9867018b4190
Create Date: 2026-06-30 17:38:48.012159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1601b5c01655'
down_revision = '9867018b4190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
