"""removed otp table

Revision ID: 9867018b4190
Revises: ee78543a6f29
Create Date: 2026-06-30 12:16:09.862019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9867018b4190'
down_revision = 'ee78543a6f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uuid'))

    op.drop_table('otp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('otp_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('otp_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders_id'], name=op.f('otp_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('otp_ibfk_2')),
    sa.PrimaryKeyConstraint('otp_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###
